---
functional: # Функциональные требования
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional: # Нефункциональные требования
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
implicit: # Неявные требования
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы

